config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :donate, only: [:new, :create, :show]
  resources :hospital, only: [:index, :new, :create, :show, :update]
  get 'hospital/:id/blood-status', to: 'hospital#edit', as: :hospital_blood_status

  get '/search', to: 'home#search'
  match '/admin' => DelayedJobWeb, :anchor => false, via: [:get, :post]
end

app/models/blood_type.rb
# == Schema Information
#
# Table name: blood_types
#
#  id         :integer          not null, primary key
#  blood_type :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BloodType < ActiveRecord::Base
  extend Enumerize
  has_and_belongs_to_many :hospitals

  enumerize :blood_type, in: [:o_positive, :o_negative, :a_positive, :a_negative, :b_positive, :b_negative, :ab_positive, :ab_negative]
  validates :blood_type, uniqueness: true
end

app/models/donor.rb
# == Schema Information
#
# Table name: donors
#
#  id             :integer          not null, primary key
#  full_name      :string
#  cell_phone     :string
#  email          :string
#  address        :string
#  lat            :float
#  long           :float
#  commute_radius :float            default(5.0)
#  blood_type     :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Donor < ActiveRecord::Base
  extend Enumerize
  geocoded_by :address, latitude: :lat, longitude: :long
  before_validation :normalize_data, :nepal_cellphone, :convert_km_to_mile
  after_validation :geo_code, if: ->(obj){ obj.address.present? and obj.address_changed? }

  validates :full_name, presence: { :message => 'Your name cannot be blank!' }
  validates :cell_phone, presence: { :message => 'Cell phone (mobile) number required for notifications.' }
  validates :address, presence: { :message => 'We need your Address.' }
  validates :blood_type, presence: { :message => 'Blood type.' }

  enumerize :blood_type, in: [:o_positive, :o_negative, :a_positive, :a_negative, :b_positive, :b_negative, :ab_positive, :ab_negative]

  def normalize_data
    self.full_name = self.full_name.try(:titleize)
    self.address = self.address.squish.try(:titleize) if self.address.present?
  end

  def geo_code
    geocode if (self.lat.nil? || self.long.nil?)
  end

  def nepal_cellphone
    cellphone = self.cell_phone.squish.gsub(/\s|\.|\-|\(|\)/, '')
    cellphone = if cellphone.start_with?('+977') && cellphone.length == 14
      cellphone
    elsif cellphone.start_with?('977') && cellphone.length == 13
      cellphone.insert(0, '+')
    elsif cellphone == '+977'
      ''
    elsif cellphone.blank?
      cellphone
    else
      cellphone.insert(0, '+977')
    end

    self.cell_phone = cellphone
  end

  def convert_km_to_mile
    self.commute_radius = self.commute_radius.to_f * 0.621371
  end

  def self.search(search)
    if search
      self.where(blood_type: search)
    else
      self.all
    end
  end

end

app/models/hospital.rb
# == Schema Information
#
# Table name: hospitals
#
#  id                   :integer          not null, primary key
#  name                 :string
#  address              :string
#  lat                  :float
#  long                 :float
#  phone                :string
#  category             :string
#  contact_person_name  :string
#  contact_person_type  :string
#  contact_person_email :string
#  contact_person_phone :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#

class Hospital < ActiveRecord::Base
  extend Enumerize
  geocoded_by :address, :latitude  => :lat, :longitude => :long
  before_validation :normalize_data
  after_validation :geo_code, if: ->(obj){ obj.address.present? and obj.address_changed? }
  has_and_belongs_to_many :blood_types

  enumerize :category, in: [:red_cross_society, :emergency_blood_transfusion, :hospital_based, :other]
  enumerize :contact_person_type, in: [:doctor, :nurse, :hospital_staff, :volunteer, :intern, :other]

  validates :name, presence: { :message => 'Name of the Hospital cannot be blank!' }
  validates :address, presence: { :message => 'Please provide the valid address.' }
  validates :category, presence: true

  def geo_code
    geocode if (self.lat.nil? || self.long.nil?)
  end

  def normalize_data
    self.name = self.name.try(:titleize)
    self.address = self.address.squish.try(:titleize) if self.address.present?
    self.contact_person_name = self.contact_person_name.squish.try(:titleize) if self.contact_person_name.present?
    self.contact_person_email = self.contact_person_email.squish.try(:downcase) if self.contact_person_email.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donate_controller.rb
class DonateController < ApplicationController
  def new
    @donor = Donor.new
  end

  def create
    @donor = Donor.where(cell_phone: donor_params[:cell_phone]).first_or_initialize(donor_params)

    if @donor.id.present?
      flash[:success] = 'We already have you on Donor List, if you have not please go ahead and donate your blood to following people /hospitals.'
      redirect_to donate_path(@donor)
    elsif @donor.save
      flash[:success] = "Thanks for being a Donor, please go ahead and donate blood to following people / hospital."
      redirect_to donate_path(@donor)
    else
      render :new
    end
  end

  def show
    @donor = Donor.find(params[:id])
    @hospitals = Hospital.near([@donor.lat , @donor.long], @donor.commute_radius, units: :km)
  end

  private
  def donor_params
    params.require(:donor).permit(:full_name, :cell_phone, :email, :address, :commute_radius, :blood_type, :lat, :long)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  ITEMS_PER_PAGE = 20

  def index

  end

  def search
    flash[:warning] = "You must specify some search criteria." if !params.has_key?(:bloodtype)
    @donors = Donor.search(params[:bloodtype]).order("created_at ASC").paginate(:page => params[:page], :per_page => ITEMS_PER_PAGE)
  end
end

app/controllers/hospital_controller.rb
class HospitalController < ApplicationController
  before_action :get_hospital, only: [:show, :edit, :update]
  def index
  end

  def new
    @hospital = Hospital.new
    @hospitals = Hospital.all.map(&:name)
  end

  def create
    @hospital = Hospital.where(name: hospital_params[:name]).first_or_initialize(hospital_params)

    if @hospital.id.present?
      flash[:success] = "We already have #{@hospital.name} on our list, please update the blood status."
      redirect_to hospital_blood_status_path(@hospital)
    elsif @hospital.save
      flash[:success] = "Thanks for registering #{@hospital.name}, please update the blood status."
      redirect_to hospital_blood_status_path(@hospital)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  private
  def hospital_params
    params.require(:hospital).permit(:name, :address, :lat, :long, :phone, :category, :contact_person_name, :contact_person_phone, :contact_person_type, :contact_person_email)
  end

  def get_hospital
    @hospital = Hospital.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donate_helper.rb
module DonateHelper
  def category_icon(hospital)
    case hospital.category
    when 'red_cross_society' then '<i class="fa fa-plus"></i>'.html_safe
    when 'hospital_based' then '<i class="fa fa-tint"></i>'.html_safe
    when 'emergency_blood_transfusion' then '<i class="fa fa-h-square"></i>'.html_safe
    when 'other' then '<i class="fa fa-bed"></i>'.html_safe
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospital_helper.rb
module HospitalHelper
end

app/views/donate/new.html.erb
<!-- Header -->
<div class="row">
  <div class="blood-header">
    <div class="container">
      <center>
        <h1 class="text-white">Donate Blood, Save Lives!</h1>
        <p class="text-white">Please complete the form below, we will notify when someone / hospital needs your blood.</p>
      </center>
    </div>
  </div>
</div>

<%= render 'partials/flash' %>
<!-- Form -->
<div class="col-sm-5" style="min-height: 120%;">
  <div class="panel panel-default">
    <div class="panel-body">
      <%= simple_form_for(@donor, url: donate_index_path, html: { class: 'form-horizontal' }) do |f| %>
        <center><legend>All fields are important.</legend></center>
        <div class="col-md-10 col-md-offset-1">
          <%= f.input :address, label: 'Address', placeholder: 'Where do you live?', hint: 'Required' %>
          <%= f.input :full_name, label: 'Full Name', hint: 'Required' %>
          <input type="hidden" id="latitude" name="donor[lat]" value="">
          <input type="hidden" id="longitude" name="donor[long]" value="">

          <div class="form-group">
            <div class="col-lg-6">
              <%= f.input :cell_phone, label: 'Cell Phone', hint: 'Required', placeholder: '+977 9811111111', input_html: {value: '(+977)'} %>
            </div>
            <div class="col-lg-6">
              <%= f.input :email, label: 'Email' %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-lg-8">
              <label class="control-label" for="commute_radius">Radius (KM)</label><br>
              <input class="form-control" type="text" name="donor[commute_radius]" id="commute_radius">
              <p class="help-block">How long can you commute to hospital ?</p>
            </div>
            <div class="col-lg-4">
              <%= f.input :blood_type %>
              <p class="help-block">Required</p>
            </div>
          </div>

          <div class="col-lg-12">
            <%= f.submit 'Submit', class: 'btn btn-default btn-lg btn-block' %>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

<!-- Map -->
<div class="col-md-7" id="map-canvas"></div>

app/views/donate/show.html.erb
<!-- Header -->
<div class="row">
  <div class="blood-header">
    <div class="container">
      <center>
        <h1 class="text-white"><%= @donor.full_name %></h1>
        <address class="text-white">
          <%= @donor.address %><br>
          <abbr title="Cell Phone"><i class="fa fa-mobile fa-2x"></i></abbr> <%= @donor.cell_phone %>&nbsp;&nbsp;
          <abbr title="Blood Type"><i class="fa fa-tint fa-2x"></i></abbr> <%= @donor.blood_type.titleize %>
        </address>
        <span class="text-white">
          <span class="quote">&ldquo;</span>
          <strong>Each pint</strong> of your blood can save as many as <strong>three lives</strong>
          <span class="quote">&rdquo;</span>
        </span>
      </center>
    </div>
  </div>
</div>

<%= render 'partials/flash' %>

<div class="container">
  <div class="page-header">
    <center><h1 id="timeline">Hospitals and  Blood Banks</h1></center>
  </div>
  <ul class="timeline">
    <% @hospitals.each_with_index do |hospital, index | %>
      <% if (index + 1).odd? %>
        <li>
          <div class="timeline-badge danger"><i class="fa fa-tint"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title"><%= hospital.name %></h4>
              <p><small class="text-muted"><i class="fa fa-map-marker"></i> <%= hospital.address %></small></p>
              <p><small class="text-muted"><i class="fa fa-phone"></i> <%= hospital.phone || 'N/A' %></small></p>
            </div>
            <div class="timeline-body">
              <p>Category: <%= hospital.category %></p>
              <p>Contact Person: <%= hospital.contact_person_name %></p>
              <p>Contact Phone: <%= hospital.contact_person_phone %></p>
            </div>
          </div>
        </li>
      <% else %>
        <li class="timeline-inverted">
          <div class="timeline-badge danger"><i class="fa fa-tint"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title"><%= hospital.name %></h4>
              <p><small class="text-muted"><i class="fa fa-map-marker"></i> <%= hospital.address %></small></p>
              <p><small class="text-muted"><i class="fa fa-phone"></i></i> <%= hospital.phone || 'N/A' %></small></p>
            </div>
            <div class="timeline-body">
              <p>Category: <%= hospital.category %></p>
              <p>Contact Person: <%= hospital.contact_person_name %></p>
              <p>Contact Phone: <%= hospital.contact_person_phone %></p>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/home/_donors.html.erb
<% @donors.each do |donor| %>
  <div class="donor">
    <h1><%= donor.full_name %></h1>
    <p><strong> Blood Type:</strong> <%= donor.blood_type.titleize %></p>
    <p><strong>Radius(KM):</strong> <%= donor.commute_radius %></p>
    <p><strong>Address:</strong> <%= donor.address %></p>
    <p><strong>Email:</strong> <%= donor.email %></p>
    <p><strong> Cell Phone:</strong> <%= donor.cell_phone %></p>
  </div>
<% end %>
<div class="search-paginate">
  <%= will_paginate @donors, class: "pagination" %>
</div>

app/views/home/index.html.erb
<header>
  <a href="/" id="logo">Blood f<img class="middle" src="/blood.png">r Nepal</a>
  <center>
  <a data-scroll href="#donate"><u>Donate</u></a>
  <!-- <a data-scroll href="#patient"><u>Patient</u></a> -->
  <a data-scroll href="#bloodbank"><u>Blood Bank</u></a>
  </center>
</header>

<section id="donate" class="hero">
  <div class="inner">
    <div class="copy">
      <h1>Save Nepal Earthquake Victims</h1>
      <p>Your blood could save multiple lives.</p>
      <br>
      <%= link_to 'Donate Blood', new_donate_path, class: 'red-btn' %>
    </div>
  </div>
</section>

<section class="content" id="bloodbank" style="background-color: #BDC3C7;">
  <div class="inner">
    <div class="copy">
    <h1>Blood Banks and Hospitals ?</h1>
    <p>Please fill out the form, we will notify the Donors with the blood type your blood bank / hospital is in need of.</p>
    <br>
    <%= link_to 'Blood Banks & Hospitals', new_hospital_path, class: 'red-btn' %>
    </div>
    </div>
  </div>
</section>

<!-- <section id="patient" class="hero">
  <div class="inner">
    <div class="copy">
    <h1>Your friend / family need blood ?</h1>
    <p>Please fill out the form, we will give you list of hospitals and people to contact for that blood type.</p>
    <br>
    <a href="" class="red-btn">Need Blood</a>
  </div>
</section> -->

<section class="content" style="background-color: black;">
  <div class="inner">
    <div class="copy">
      <center><a href="http://opensourcefornepal.github.io/" target="_blank"><%= image_tag("logo.png", size: "50x50") %></a></center>
      <h1 class="text-white">Open Source for Nepal</h1>
      <p><%= render 'partials/social_share' %></p>
    </div>
  </div>
</section>

app/views/home/search.html.erb
<!-- Header -->
<header>
  <a href="/" id="logo">Blood f<img class="middle" src="/blood.png">r Nepal</a>
</header>


<%= form_tag("/search", :method => "get", class: 'search-from') do %>
	<div class="col-lg-12">
    <div class="field form-group inline">
		    <%= select_tag :bloodtype, options_for_select(Donor.blood_type.values), class: 'select form-control'%>
    </div>
    <div class="field form-group inline">
      <%= submit_tag "Search for Donors", :name => nil, class: "btn btn-default btn-lg btn-block" %>
    </div>
	</div>
<% end %>
<br>

<div id="donors" class="row search-results">
  <% if @donors.count == 0 %>
    <p>No Donors Found.</p>
  <% else %>
    <%= render 'donors' %>
  <% end %>
</div>

app/views/home/search.js.erb
$("#donors").html("<%= escape_javascript(render("donors")) %>");

app/views/hospital/create.html.erb
<h1>Hospital#create</h1>
<p>Find me in app/views/hospital/create.html.erb</p>

app/views/hospital/edit.html.erb
<!-- Header -->
<div class="row">
  <div class="blood-header">
    <div class="container">
      <center>
        <h1 class="text-white"><%= @hospital.name %></h1>
        <address class="text-white">
          <%= @hospital.address %><br>
          <abbr title="Phone"><i class="fa fa-phone-square fa-lg"></i></abbr> <%= @hospital.phone %>
        </address>
        <span class="text-white">
          Please update the blood status.
        </span>
      </center>
    </div>
  </div>
</div>

<%= render 'partials/flash' %>

app/views/hospital/index.html.erb
<!-- Header -->
<div class="row">
  <div class="blood-header">
    <div class="container">
      <center>
        <h1 class="text-white">Donate Blood, Save Lives!</h1>
        <span class="text-white">
          <span class="quote">&ldquo;</span>
          <strong>Each pint</strong> of your blood can save as many as <strong>three lives</strong>
          <span class="quote">&rdquo;</span>
        </span>
      </center>
    </div>
  </div>
</div>

<%= render 'partials/flash' %>

app/views/hospital/new.html.erb
<!-- Header -->
<div class="row">
  <div class="blood-header">
    <div class="container">
      <center>
        <h1 class="text-white">Hospital and/or Blood Bank</h1>
        <span class="text-white">
          Please complete the form below, after you do that we expect the status of blood need in this hospital / blood bank to be updated periodically. We will notify and incourage the blood near by blood donors come and donate blood at your facility.
        </span>
      </center>
    </div>
  </div>
</div>

<%= render 'partials/flash' %>

<!-- Form -->
<div class="col-sm-5" style="min-height: 120%;">
  <div class="panel panel-default">
    <div class="panel-body">
      <%= simple_form_for(@hospital, url: hospital_index_path, html: { class: 'form-horizontal' }) do |f| %>
        <center><legend>Hospital / Blood Bank</legend></center>
        <div class="col-md-10 col-md-offset-1">
          <%= f.input :name, label: 'Name',placeholder: 'Hospital / Blood Bank Name (search)', hint: 'Required' %>
          <%= f.input :address, label: 'Address', placeholder: 'Hospital / Blood Bank Address', hint: 'Required' %>
          <input type="hidden" id="latitude" name="hospital[lat]" value="">
          <input type="hidden" id="longitude" name="hospital[long]" value="">

          <div class="form-group">
            <div class="col-lg-6">
              <%= f.input :phone, label: 'Phone Number', hint: 'Important', placeholder: '+977 0000000000', input_html: {value: '(+977)'} %>
            </div>
            <div class="col-lg-6">
              <%= f.input :category %>
            </div>
          </div>

          <center><legend>Contact Person</legend></center>
          <div class="form-group">
            <div class="col-lg-6">
              <%= f.input :contact_person_name, label: 'Name', hint: 'Important', placeholder: 'Contact Person Name'%>
            </div>
            <div class="col-lg-6">
              <%= f.input :contact_person_phone, label: 'Phone', hint: 'Important', placeholder: 'Contact Person Phone'%>
            </div>

            <div class="col-lg-6">
              <%= f.input :contact_person_type, label: 'Occupation', hint: 'Important' %>
            </div>
            <div class="col-lg-6">
              <%= f.input :contact_person_email, label: 'Email', hint: 'Important', placeholder: 'Contact Person Email'%>
            </div>

          </div>

          <div class="col-lg-12">
            <%= f.submit 'Submit', class: 'btn btn-default btn-lg btn-block' %>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

<!-- Map -->
<div class="col-md-7" id="map-canvas" style="height: 110%;"></div>

<script type="text/javascript">
  var input = document.getElementById("hospital_name");
  new Awesomplete(input, {
    list: <%= raw @hospitals %>
  });
</script>

app/views/hospital/show.html.erb
<h1>Hospital#show</h1>
<p>Find me in app/views/hospital/show.html.erb</p>

app/views/layouts/donate.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel='icon' href='/blood.ico' sizes="16x16">
    <link rel="apple-touch-icon-precomposed" href="https://s3-ap-southeast-1.amazonaws.com/bloodfornepal/apple-touch-icon.png" />
    <%= display_meta_tags title: 'Donate Blood, Save Nepal Earthquake Victims.',
      description: 'Your 1 pint of blood could save 3 victims of Earthquake in Nepal. Donate Blood, Save Lives!',
      keywords: 'Donate, Blood, Nepal, Earthquake, Victims, Save Lives',
      viewport: 'width=device-width, initial-scale=1.0, maximum-scale=1.0',
      canonical: 'http://bloodfornepal.org',
      og: { title: 'Donate Blood, Save Nepal Earthquake Victims.', image: 'https://s3-ap-southeast-1.amazonaws.com/bloodfornepal/supportnepal_optimized.jpg', description: 'Your 1 pint of blood could save 3 victims of Earthquake in Nepal. Donate, Blood Save Lives!' } %>

    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.4/cosmo/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.6/animate.min.css">
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/sweetalert/0.5.0/sweet-alert.css">
    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tags %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="//maps.googleapis.com/maps/api/js?v=3.exp&signed_in=false&libraries=places"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/sweetalert/0.5.0/sweet-alert.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.mask/0.9.0/jquery.mask.min.js"></script>
    <%= javascript_include_tag "donate" %>
  </head>
  <body>
    <header>
      <a href="/" id="logo">Blood f<img src="/blood.png">r Nepal</a>
    </header>

    <%= yield %>

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel='icon' href='/blood.ico' sizes="16x16">
    <link rel="apple-touch-icon-precomposed" href="https://s3-ap-southeast-1.amazonaws.com/bloodfornepal/apple-touch-icon.png" />
    <%= display_meta_tags title: 'Donate Blood, Save Nepal Earthquake Victims.',
      description: 'Your 1 pint of blood could save 3 victims of Earthquake in Nepal. Donate Blood, Save Lives!',
      keywords: 'Donate, Blood, Nepal, Earthquake, Victims, Save Lives',
      viewport: 'width=device-width, initial-scale=1.0, maximum-scale=1.0',
      canonical: 'http://bloodfornepal.org',
      og: { title: 'Donate Blood, Save Nepal Earthquake Victims.', image: 'https://s3-ap-southeast-1.amazonaws.com/bloodfornepal/supportnepal_optimized.jpg', description: 'Your 1 pint of blood could save 3 victims of Earthquake in Nepal. Donate, Blood Save Lives!' } %>

  <%= stylesheet_link_tag 'home' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
  <%= javascript_include_tag 'home', media: 'all' %>
  <script>
    smoothScroll.init();
  </script>
</body>
</html>

app/views/layouts/hospital.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel='icon' href='/blood.ico' sizes="16x16">
    <link rel="apple-touch-icon-precomposed" href="https://s3-ap-southeast-1.amazonaws.com/bloodfornepal/apple-touch-icon.png" />
    <%= display_meta_tags title: 'Donate Blood, Save Nepal Earthquake Victims.',
      description: 'Your 1 pint of blood could save 3 victims of Earthquake in Nepal. Donate Blood, Save Lives!',
      keywords: 'Donate, Blood, Nepal, Earthquake, Victims, Save Lives',
      viewport: 'width=device-width, initial-scale=1.0, maximum-scale=1.0',
      canonical: 'http://bloodfornepal.org',
      og: { title: 'Donate Blood, Save Nepal Earthquake Victims.', image: 'https://s3-ap-southeast-1.amazonaws.com/bloodfornepal/supportnepal_optimized.jpg', description: 'Your 1 pint of blood could save 3 victims of Earthquake in Nepal. Donate, Blood Save Lives!' } %>

    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.4/cosmo/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.6/animate.min.css">
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/sweetalert/0.5.0/sweet-alert.css">
    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tags %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="//maps.googleapis.com/maps/api/js?v=3.exp&signed_in=false&libraries=places"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/sweetalert/0.5.0/sweet-alert.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.mask/0.9.0/jquery.mask.min.js"></script>
    <%= javascript_include_tag "hospital" %>
  </head>
  <body>
    <header>
      <a href="/" id="logo">Blood f<img src="/blood.png">r Nepal</a>
    </header>

    <%= yield %>

  </body>
</html>

app/views/partials/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-dismissible alert-<%= key %>">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <center><strong><p class="animated fadeInUp"><%= value.html_safe %></p></strong></center>
  </div>
<% end %>

app/views/partials/_nav.html.erb
<div class="col s12 red lighten-1 navigation">
  <span>Blood Donation</span>
</div>